export const RETRIVE_SHOWS_DATA_FAIL = "RETRIVE_SHOWS_DATA_FAIL";
export const SHOWS_DATA = "SHOWS_DATA";
export const SHOW_DETAILS_FAIL = "SHOW_DETAILS_FAIL";
export const SHOW_DETAILS = "SHOW_DETAILS";
export const SEARCH_SHOW_FAIL = "SEARCH_SHOW_FAIL";
export const SEARCH_SHOW = "SEARCH_SHOW";
export const SERVER_ERROR = "SERVER_ERROR";